### PR TITLE
fix : `num_limbs_log2_ceil`

### PR DESCRIPTION
**Pull request by enricobottazzi**

### CODE REVIEW

**Comment by jonathanpwang** [comment]
Could you explain this PR? `num_limbs_log2_ceil` is not a function I believe.
`bit_length` can be 1 greater than `log2_ceil`, if that is the fix?

**Comment by enricobottazzi** [comment]
You're right. I meant to use [`log2_ceil()` util](https://github.com/axiom-crypto/halo2-lib/blob/93f2567c47602e5c8a2cdd24bb17be54cf3f6c2d/halo2-base/src/utils/mod.rs#L161) instead. 

As you mentioned, the fix relates to the possible discrepancy between `bit_length` and `log2_ceil`. 

If this makes sense to you, I can go ahead and fix it.

**Comment by jonathanpwang** [comment]
Ok I checked and I think using `log2_ceil` from `util` would be correct. Please make the fix

**Review by jonathanpwang — APPROVED** [review]
LGTM!

**Pull request merged**
